-
  request:
    url: https://b2b2c-api-test.mall4j.com/p/shopCart/changeItem
    headers: # 请求头
      authorization: QdNtoxR9/4LyMEJU4DWPq1gy2wAjKyvuD530yZrF/TPCo7ACMn7LlLbPSiWmsBlG
    params:
      basketId: 0
      count: 1
      prodId: 978
      shopId: 106
      skuId: 2385
      distributionCardNo: ''